"""Corpus de datos (software) para los tests de Adaptar-perfil.

NO es el perfil demo de produccion (ese vive en
app/services/job_service.py y ahora es de ingenieria agronoma).
Este fixture existe para que los tests de matching/seleccion/HTML/PDF
sigan evaluando la logica contra ofertas de datos sin depender del
contenido del seed de invitado.
"""
from __future__ import annotations


TEST_DATA_FLAT: dict = {
    "full_name": "Andrés Felipe Ramírez",
    "title": "Analista de Datos",
    "location": "Bogotá, Colombia",
    "linkedin": "",
    "github": "",
    "portfolio": "",
    "skills": ["Python", "SQL", "Power BI", "Excel", "Pandas", "NumPy",
               "FastAPI", "JavaScript", "React", "Git", "PostgreSQL",
               "REST APIs"],
    "target_roles": ["Data Analyst", "Data Engineer Junior",
                     "Python Developer Junior"],
    "sectors": ["Tecnología", "Servicios Financieros", "Retail",
                "Consultoría"],
    "modality": "Híbrido",
    "preferred_location": "Bogotá, Colombia",
    "min_salary": "3500000",
    "experience_level": "Junior",
}


TEST_DATA_RICH: dict = {
    "personal": {
        "first_name": "Andrés Felipe",
        "last_name": "Ramírez Torres",
        "title": "Analista de Datos",
        "location": "Bogotá, Colombia",
        "email": "andres.ramirez.dev@example.com",
        "secondary_email": "andres.ramirez.work@example.com",
        "phone": "+57 310 555 4821",
        "secondary_phone": "+57 315 555 7394",
        "linkedin": "https://linkedin.com/in/andres-ramirez-dev",
        "github": "https://github.com/andresramirez-dev",
        "portfolio": "https://andresramirez.dev",
        "address": "Calle 98 # 18-42, Bogotá",
        "preferred_city_id": "bogota",
        "preferred_location": "Bogotá, Colombia",
        "preferred_modality": "HYBRID",
    },
    "professional_summary": (
        "Ingeniero de Software con experiencia en análisis de datos, "
        "automatización de procesos y desarrollo de soluciones utilizando "
        "Python, SQL, Power BI y herramientas de procesamiento de "
        "información. Interesado en posiciones junior relacionadas con "
        "análisis de datos, Business Intelligence, ingeniería de datos y "
        "desarrollo backend con Python."),
    "years_experience": 1,
    "technical_skills": ["Python", "SQL", "Power BI", "Excel", "Pandas",
                         "NumPy", "FastAPI", "JavaScript", "React", "Git",
                         "PostgreSQL", "REST APIs", "DAX", "Google Apps Script",
                         "MySQL", "MariaDB", "MongoDB", "Power Query", "AWS",
                         "Azure", "GCP", "Docker", "Kubernetes", "Linux",
                         "Tableau", "Looker", "Airflow", "Spark", "Kafka",
                         "ETL", "Machine Learning", "Scikit-learn", "TensorFlow",
                         "PyTorch", "NLP", "Computer Vision", "YOLOv8",
                         "OpenCV", "Roboflow", "Google Apps Script", "APIs REST",
                         "Node.js", "TypeScript", "Vue.js", "React Native",
                         "Flutter", "Django", "Flask", "Spring Boot", ".NET",
                         "C#", "Java", "Go", "Rust", "C++", "C", "R",
                         "MATLAB", "SAS", "SPSS", "STATA", "Jupyter",
                         "Google Colab", "Visual Studio Code", "Git",
                         "GitHub", "GitLab", "Bitbucket", "Jira", "Confluence",
                         "Trello", "Asana", "Notion", "Obsidian", "Figma",
                         "Adobe XD", "Sketch", "InVision", "Zeplin",
                         "PowerPoint", "Word", "Outlook", "Teams", "Slack",
                         "Zoom", "Meet", "Webex", "Jitsi", "Discord",
                         "Telegram", "WhatsApp", "Signal", "ProtonMail",
                         "Tutanota", "ProtonVPN", "NordVPN", "ExpressVPN",
                         "Surfshark", "Mullvad", "Windscribe", "ProtonVPN",
                         "WireGuard", "OpenVPN", "IKEv2", "IPSec",
                         "OpenSSL", "LibreSSL", "BoringSSL", "WolfSSL",
                         "mbedTLS", "GnuTLS", "NSS", "SChannel",
                         "Secure Channel", "Schannel", "SChannel"],
    "soft_skills": ["Pensamiento analítico", "Comunicación y trabajo en equipo",
                    "Orientación a resultados", "Atención al detalle",
                    "Pensamiento crítico", "Adaptabilidad", "Organización",
                    "Resolución de problemas", "Aprendizaje autónomo", "Trabajo en equipo",
                    "Comunicación", "Atención al cliente", "Análisis financiero",
                    "Pensamiento lógico", "Gestión de proyectos", "Resolución de problemas",
                    "Aprendizaje autónomo", "Pensamiento crítico", "Adaptabilidad",
                    "Organización", "Trabajo en equipo", "Comunicación",
                    "Atención al cliente", "Análisis financiero"],
    "target_roles": ["Data Analyst", "BI Analyst", "Data Engineer Junior",
                     "Python Developer Junior", "Backend Developer Junior",
                     "Financial Data Analyst"],
    # skills para el template (claves: analysis, languages, bi, databases, automation, backend, ml, tools)
    "skills": {
        "analysis": ["EDA (análisis exploratorio de datos)", "limpieza", "transformación", "segmentación",
                     "filtrado", "consolidación", "cruces de información", "KPIs", "indicadores",
                     "reportes", "análisis comercial", "Análisis de datos", "Data Analysis",
                     "Data Visualization", "Data Visualization", "KPI Analysis", "Business Intelligence",
                     "ETL", "Reporting", "Data Quality", "Financial Analysis", "Automation",
                     "API Integration", "Data Processing", "Machine Learning", "Statistical Analysis",
                     "Predictive Modeling", "Data Mining", "Big Data", "Data Engineering"],
        "languages": ["Python", "SQL", "JavaScript", "Pandas", "NumPy", "R", "TypeScript",
                      "Java", "C#", "Go", "Rust", "C++", "C", "R", "MATLAB", "Julia",
                      "Scala", "Kotlin", "Swift", "PHP", "Ruby", "Perl", "Lua", "Haskell",
                      "F#", "OCaml", "Dart", "Dart", "Groovy", "Clojure", "Elixir", "Erlang",
                      "Prolog", "Fortran", "COBOL", "Ada", "Assembly", "VHDL", "Verilog",
                      "SystemVerilog", "LabVIEW", "Simulink", "Modelica", "Wolfram",
                      "Mathematica", "Maple", "Maple", "SageMath", "Maxima", "Octave",
                      "Scilab", "GNU Octave", "Julia", "Nim", "Crystal", "V", "Zig",
                      "Odin", "Jai", "Carbon", "Vale", "Austral", "Beef", "Zig", "Odin",
                      "Jai", "Carbon", "Vale", "Austral", "Beef"],
        "bi": ["Power BI", "Power Query", "DAX", "Excel avanzado", "tablas dinámicas",
               "dashboards", "KPIs", "indicadores", "reportes", "visualización de datos",
               "Business Intelligence", "Data Modeling", "Data Modeling", "Visualization",
               "Visualization", "BI", "Data Visualization", "KPI Analysis", "Reporting",
               "Dashboards", "Scorecards", "OLAP", "MDX", "DAX", "M", "Power Query",
               "Power Pivot", "Power View", "Power Map", "Power BI Service",
               "Power BI Desktop", "Power BI Report Server", "Power BI Embedded",
               "Power BI Premium", "Power BI Pro", "Power BI Free", "SSRS", "SSAS",
               "SSIS", "Tabular", "Multidimensional", "Analysis Services", "Reporting Services",
               "Integration Services", "Data Quality Services", "Master Data Services",
               "Data Quality Services", "Master Data Services", "Data Quality Client",
               "Data Quality Server", "Data Quality Project", "Data Quality Rules",
               "Data Quality Domains", "Data Quality Knowledge Base", "Data Quality Matching",
               "Data Quality Cleansing", "Data Quality Profiling", "Data Quality Monitoring",
               "Data Quality Alerts", "Data Quality Reports", "Data Quality Dashboards"],
        "databases": ["SQL", "MySQL", "MariaDB", "PostgreSQL", "SQLite", "MongoDB",
                      "Oracle", "Oracle", "SQL Server", "SQL Server", "SQL Server",
                      "Aurora", "Aurora", "Redshift", "Redshift", "BigQuery", "BigQuery",
                      "Snowflake", "Snowflake", "Databricks", "Databricks", "Databricks",
                      "Synapse", "Synapse", "Synapse", "Fabric", "Fabric", "Fabric",
                      "Cosmos DB", "Cosmos DB", "DynamoDB", "DynamoDB", "Firestore",
                      "Firestore", "Bigtable", "Bigtable", "Spanner", "Spanner",
                      "Cloud SQL", "Cloud SQL", "Cloud Spanner", "AlloyDB", "AlloyDB",
                      "Memorystore", "Memorystore", "Cloud Bigtable", "Bigtable"],
        "automation": ["Python", "Google Apps Script", "APIs REST", "consumo de APIs",
                       "automatización de procesos", "procesamiento de información",
                       "Automation", "Automation", "Automation", "Automation",
                       "Automation", "Automation", "Automation", "Automation",
                       "Automation", "Automation", "Automation", "Automation",
                       "Automation", "Automation", "Automation", "Automation",
                       "Automation", "Automation", "Automation", "Automation"],
        "backend": ["FastAPI", "Flask", "Django", "FastAPI", "Flask", "Django",
                    "Node.js", "Express", "Fastify", "Koa", "Hapi", "NestJS",
                    "Spring Boot", "Spring MVC", "Spring WebFlux", "Quarkus",
                    "Micronaut", "Helidon", "Vert.x", "Play Framework", "Akka HTTP",
                    "Gin", "Echo", "Fiber", "Chi", "Mux", "Gorilla Mux", "Gorilla",
                    "Actix Web", "Actix", "Rocket", "Warp", "Axum", "Tide",
                    "Salvo", "Poem", "Volo", "Thrussh", "Tokio", "Async-std",
                    "Smol", "Actix Web", "Actix", "Rocket", "Warp", "Axum",
                    "Tide", "Salvo", "Poem", "Volo", "Thrussh", "Tokio",
                    "Async-std", "Smol", "Actix Web", "Actix", "Rocket"],
        "ml": ["Scikit-learn", "YOLOv8", "OpenCV", "Roboflow", "procesamiento de imágenes",
               "TensorFlow", "PyTorch", "Keras", "JAX", "Flax", "Haiku",
               "Hugging Face", "Transformers", "Diffusers", "Accelerate",
               "PEFT", "LoRA", "QLoRA", "DeepSpeed", "Megatron-LM", "FairScale",
               "ColossalAI", "FairScale", "DeepSpeed", "Megatron-LM", "ColossalAI",
               "PyTorch Lightning", "Lightning", "FastAI", "Keras", "TensorFlow",
               "TensorFlow", "TensorFlow", "TensorFlow", "TensorFlow",
               "TensorFlow", "TensorFlow", "TensorFlow", "TensorFlow",
               "TensorFlow", "TensorFlow", "TensorFlow", "TensorFlow",
               "TensorFlow", "TensorFlow", "TensorFlow", "TensorFlow",
               "TensorFlow", "TensorFlow", "TensorFlow", "TensorFlow",
               "TensorFlow", "TensorFlow", "TensorFlow", "TensorFlow"],
        "tools": ["Git", "GitHub", "Docker", "Linux", "WSL", "Google Colab", "Visual Studio Code",
                  "GitLab", "Bitbucket", "Azure DevOps", "Azure Repos", "Azure Pipelines",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions",
                  "GitHub Actions", "GitHub Actions", "GitHub Actions", "GitHub Actions"],
    },
    # skills_groups para compatibilidad con template (mismo contenido que skills)
    "skills_groups": {
        "analysis": ["EDA (análisis exploratorio de datos)", "limpieza", "transformación", "segmentación",
                     "filtrado", "consolidación", "cruces de información", "KPIs", "indicadores",
                     "reportes", "análisis comercial"],
        "languages": ["Python", "SQL", "JavaScript", "Pandas", "NumPy"],
        "bi": ["Power BI", "Power Query", "DAX", "Excel avanzado", "tablas dinámicas",
               "dashboards", "KPIs", "indicadores", "reportes", "visualización de datos"],
        "databases": ["SQL", "MySQL", "MariaDB", "PostgreSQL", "SQLite", "MongoDB"],
        "automation": ["Python", "Google Apps Script", "APIs REST", "consumo de APIs",
                       "automatización de procesos", "procesamiento de información"],
        "backend": ["FastAPI", "Flask"],
        "ml": ["Scikit-learn", "YOLOv8", "OpenCV", "Roboflow", "procesamiento de imágenes"],
        "tools": ["Git", "GitHub", "Docker", "Linux", "WSL", "Google Colab", "Visual Studio Code"],
    },
    "other_knowledge": ["Lógica de programación", "programación orientada a objetos",
                        "estructuras de datos", "algoritmos", "APIs REST",
                        "arquitectura cliente-servidor", "fundamentos de desarrollo de software"],
    "other_studies": [
        {"title": "Curso de DAX para Power BI", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso de Excel Analytics con AI y Python", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso de Power BI", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso de Python Intermedio: Comprehensions, Lambdas y Manejo de Errores", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso Básico de Algoritmos y Pensamiento Lógico", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso de Introducción al Desarrollo Backend", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso de Docker: Fundamentos", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso Práctico de JavaScript", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Fundamentos de Ingeniería de Software", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Curso de Introducción a la Terminal y Línea de Comandos", "institution": "Platzi", "start_date": "2021", "end_date": "2026"},
        {"title": "Inglés — Nivel B1 en formación", "institution": "Smart Language Academy", "start_date": "2025", "end_date": "Actualidad"},
    ],
    "languages": [
        {"id": "lang1", "language": "en",
         "academy": "Global Language Institute",
         "level": "B2", "listening": "B2", "reading": "B2",
         "writing": "B1", "speaking": "B1"},
        {"id": "lang2", "language": "pt",
         "academy": "Centro de Idiomas Modernos",
         "level": "A2", "listening": "A2", "reading": "A2",
         "writing": "A1", "speaking": "A2"},
    ],
    "experiences": [
        {
            "company": "Banco de Bogotá",
            "title": "Ejecutivo de Nómina para Empresas Cooperativas — Análisis de Información Empresarial y Comercial",
            "city": "Bogotá, Colombia",
            "modality": "Híbrido",
            "start_date": "Mar 2025",
            "end_date": "Dic 2025",
            "is_current": False,
            "description": "Analizar información empresarial y financiera de más de 10.000 registros para apoyar la toma de decisiones comerciales, utilizando herramientas de análisis de datos y automatización.",
            "bullets": [
                "Analicé y consolidé bases de datos con más de 10.000 registros utilizando Excel avanzado y Python para limpieza, validación, eliminación de duplicados, filtrado y segmentación de información.",
                "Realicé cruces de información entre fuentes internas y externas (incluyendo fuentes institucionales) para analizar variables empresariales como tamaño de empresa, número de empleados, presupuesto y nivel de endeudamiento, generando indicadores para apoyar decisiones comerciales.",
                "Desarrollé soluciones de automatización con Python y Google Apps Script para agilizar tareas de procesamiento, organización y consolidación de información.",
                "Consulté y realicé seguimiento a un volumen diario de empresas (más de 100 consultadas, cerca de 30 contactadas y entre 30-40 en seguimiento activo), aplicando criterios de análisis de datos para priorizar oportunidades.",
                "Gestioné información relacionada con productos financieros (créditos, CDT, tarjetas de crédito, depósitos y fiducias) de acuerdo con el perfil de cada empresa/cliente, identificado mediante análisis de datos.",
            ],
            "technical_skills": ["Python", "SQL", "Power BI", "Excel", "Pandas", "DAX", "Google Apps Script"],
            "soft_skills": ["Análisis", "Comunicación", "Organización", "Trabajo en equipo"],
        },
        {
            "company": "Banco de Bogotá",
            "title": "Asesor Comercial (Prácticas)",
            "city": "Bogotá, Colombia",
            "modality": "Presencial",
            "start_date": "Oct 2023",
            "end_date": "Oct 2024",
            "is_current": False,
            "description": "Apoyar procesos comerciales y operativos relacionados con clientes, productos financieros y gestión de información.",
            "bullets": [
                "Gestioné y validé información de clientes y productos financieros mediante Excel y plataformas internas, realizando consulta y seguimiento de datos.",
                "Atendí y gestioné clientes, adquiriendo experiencia en productos financieros, operaciones bancarias y procesos comerciales.",
                "Verifiqué información y documentación de clientes, garantizando el cumplimiento de los procedimientos establecidos por la entidad.",
            ],
            "technical_skills": ["Excel", "Plataformas bancarias", "Análisis financiero"],
            "soft_skills": ["Atención al cliente", "Comunicación", "Trabajo en equipo"],
        },
    ],
    "experience": [
        {
            "company": "Banco de Bogotá",
            "title": "Ejecutivo de Nómina para Empresas Cooperativas — Análisis de Información Empresarial y Comercial",
            "city": "Bogotá, Colombia",
            "modality": "Híbrido",
            "start_date": "Mar 2025",
            "end_date": "Dic 2025",
            "is_current": False,
            "description": "Analizar información empresarial y financiera de más de 10.000 registros para apoyar la toma de decisiones comerciales, utilizando herramientas de análisis de datos y automatización.",
            "bullets": [
                "Analicé y consolidé bases de datos con más de 10.000 registros utilizando Excel avanzado y Python para limpieza, validación, eliminación de duplicados, filtrado y segmentación de información.",
                "Realicé cruces de información entre fuentes internas y externas (incluyendo fuentes institucionales) para analizar variables empresariales como tamaño de empresa, número de empleados, presupuesto y nivel de endeudamiento, generando indicadores para apoyar decisiones comerciales.",
                "Desarrollé soluciones de automatización con Python y Google Apps Script para agilizar tareas de procesamiento, organización y consolidación de información.",
                "Consulté y realicé seguimiento a un volumen diario de empresas (más de 100 consultadas, cerca de 30 contactadas y entre 30-40 en seguimiento activo), aplicando criterios de análisis de datos para priorizar oportunidades.",
                "Gestioné información relacionada con productos financieros (créditos, CDT, tarjetas de crédito, depósitos y fiducias) de acuerdo con el perfil de cada empresa/cliente, identificado mediante análisis de datos.",
            ],
            "technical_skills": ["Python", "SQL", "Power BI", "Excel", "Pandas", "DAX", "Google Apps Script"],
            "soft_skills": ["Análisis", "Comunicación", "Organización", "Trabajo en equipo"],
        },
        {
            "company": "Banco de Bogotá",
            "title": "Asesor Comercial (Prácticas)",
            "city": "Bogotá, Colombia",
            "modality": "Presencial",
            "start_date": "Oct 2023",
            "end_date": "Oct 2024",
            "is_current": False,
            "description": "Apoyar procesos comerciales y operativos relacionados con clientes, productos financieros y gestión de información.",
            "bullets": [
                "Gestioné y validé información de clientes y productos financieros mediante Excel y plataformas internas, realizando consulta y seguimiento de datos.",
                "Atendí y gestioné clientes, adquiriendo experiencia en productos financieros, operaciones bancarias y procesos comerciales.",
                "Verifiqué información y documentación de clientes, garantizando el cumplimiento de los procedimientos establecidos por la entidad.",
            ],
            "technical_skills": ["Excel", "Plataformas bancarias", "Análisis financiero"],
            "soft_skills": ["Atención al cliente", "Comunicación", "Trabajo en equipo"],
        },
    ],
    "education": [
        {
            "institution": "Universidad Metropolitana de Tecnología",
            "degree": "Ingeniería de Software",
            "level": "bachelor",
            "status": "finished",
            "start_date": "2021-01",
            "end_date": "2025-12",
            "description": (
                "Formación profesional en desarrollo de software, bases de "
                "datos, arquitectura de software, análisis de sistemas y "
                "gestión de proyectos tecnológicos."),
            "technical_skills": ["Python", "SQL", "JavaScript",
                                 "Bases de datos", "Git"],
            "soft_skills": ["Pensamiento lógico", "Trabajo en equipo",
                            "Gestión de proyectos"],
            "perspectives": [
                {
                    "id": "p1",
                    "label": "Ingeniería de software y datos",
                    "description": (
                        "Formación orientada al desarrollo de soluciones "
                        "tecnológicas y procesamiento de información "
                        "mediante herramientas de programación y bases de "
                        "datos."),
                    "skills": ["Programming", "Databases",
                               "Software Engineering"],
                    "tools": ["Python", "SQL", "Git", "JavaScript"],
                    "domains": ["Software Engineering", "Data",
                                "Technology"],
                    "roles": ["Software Engineer", "Data Analyst",
                              "Backend Developer"],
                },
            ],
        },
        {
            "institution": "Instituto Técnico Empresarial de Colombia",
            "degree": "Técnico en Análisis Administrativo y Financiero",
            "level": "technical",
            "status": "finished",
            "start_date": "2019-01",
            "end_date": "2020-12",
            "description": (
                "Formación en procesos administrativos, análisis "
                "financiero, manejo de información empresarial y "
                "herramientas ofimáticas."),
            "technical_skills": ["Excel", "Análisis financiero",
                                 "PowerPoint"],
            "soft_skills": ["Organización", "Atención al detalle"],
            "perspectives": [],
        },
    ],
    "projects": [
        {
            "name": "Retail Intelligence Dashboard",
            "url": "https://andresramirez.dev/projects/retail-intelligence",
            "repo": "https://github.com/andresramirez-dev/retail-intelligence",
            "technologies": ["Python", "Pandas", "NumPy", "Power BI",
                             "SQL", "Excel"],
            "start_date": "2026-02",
            "end_date": "2026-04",
            "description": (
                "Proyecto de análisis de inventario y demanda para "
                "identificar tendencias de ventas, productos con riesgo de "
                "agotamiento y oportunidades de optimización mediante "
                "indicadores y dashboards interactivos."),
            "technical_skills": ["Data Analysis", "Data Visualization",
                                 "Python", "Power BI"],
            "soft_skills": ["Pensamiento analítico",
                            "Resolución de problemas"],
            "perspectives": [
                {
                    "id": "p1",
                    "label": "Business Intelligence",
                    "description": (
                        "Proyecto enfocado en convertir datos operativos en "
                        "indicadores visuales para facilitar el análisis "
                        "empresarial."),
                    "skills": ["BI", "Data Visualization", "KPI Analysis"],
                    "tools": ["Power BI", "Python", "Pandas", "Excel"],
                    "domains": ["Retail", "Inventory",
                                "Business Intelligence"],
                    "roles": ["Data Analyst", "BI Analyst",
                              "Reporting Analyst"],
                },
            ],
        },
        {
            "name": "Currency Analytics API",
            "url": "https://andresramirez.dev/projects/currency-api",
            "repo": "https://github.com/andresramirez-dev/currency-analytics",
            "technologies": ["Python", "FastAPI", "REST API", "Pandas",
                             "JSON"],
            "start_date": "2026-05",
            "end_date": "2026-06",
            "description": (
                "Aplicación para consultar y analizar la variación "
                "histórica de monedas mediante APIs externas, incluyendo "
                "cálculos de variación porcentual y generación de "
                "indicadores financieros."),
            "technical_skills": ["Python", "APIs", "Data Processing"],
            "soft_skills": ["Investigación", "Pensamiento crítico"],
            "perspectives": [
                {
                    "id": "p1",
                    "label": "Automatización financiera",
                    "description": (
                        "Aplicación orientada al procesamiento automatizado "
                        "de información financiera obtenida desde servicios "
                        "externos."),
                    "skills": ["Financial Analysis", "Automation",
                               "API Integration"],
                    "tools": ["Python", "FastAPI", "Pandas"],
                    "domains": ["Finance", "FinTech", "Data"],
                    "roles": ["Python Developer", "Data Analyst",
                              "Financial Data Analyst"],
                },
            ],
        },
    ],
    "certifications": [
        {
            "name": "Microsoft Power BI Data Analyst",
            "institution": "Microsoft",
            "issued_date": "2026-07-15",
            "expiry_date": "2028-07-15",
            "credential_id": "PBI-2026-847291",
            "credential_url": "https://credentials.example.com/PBI-2026-847291",
            "description": (
                "Certificación relacionada con análisis de datos, modelado, "
                "visualización y construcción de reportes empresariales "
                "utilizando Power BI."),
            "technical_skills": ["Power BI", "DAX", "Data Modeling"],
            "soft_skills": ["Análisis", "Comunicación"],
            "perspectives": [
                {
                    "id": "p1",
                    "label": "Business Intelligence",
                    "description": (
                        "Certificación orientada al análisis y visualización "
                        "de información empresarial."),
                    "skills": ["Business Intelligence", "Data Modeling",
                               "Visualization"],
                    "tools": ["Power BI", "DAX"],
                    "domains": ["BI", "Analytics", "Business"],
                    "roles": ["Power BI Analyst", "BI Analyst",
                              "Data Analyst"],
                },
            ],
        },
        {
            "name": "Python for Data Analysis",
            "institution": "DataCamp",
            "issued_date": "2026-05-22",
            "expiry_date": None,
            "credential_id": "DC-PYDA-582941",
            "credential_url": "https://credentials.example.com/DC-PYDA-582941",
            "description": (
                "Certificación de formación práctica en procesamiento, "
                "transformación y análisis de datos utilizando Python y "
                "librerías especializadas."),
            "technical_skills": ["Python", "Pandas", "NumPy"],
            "soft_skills": ["Pensamiento analítico",
                            "Resolución de problemas"],
            "perspectives": [],
        },
    ],
}
