// Ciudades y municipios de Colombia para autocompletado.
// Las principales van primero: se muestran al abrir el desplegable.
export const COLOMBIAN_CITIES: string[] = [
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Bucaramanga",
  "Pereira",
  "Manizales",
  "Armenia",
  "Santa Marta",
  "Cúcuta",
  "Ibagué",
  "Neiva",
  "Villavicencio",
  "Pasto",
  "Montería",
  "Valledupar",
  "Tunja",
  "Popayán",
  "Sincelejo",
  "Riohacha",
  "Quibdó",
  "Leticia",
  "San Andrés",
  // Municipios y resto de capitales.
  "Soacha",
  "Bello",
  "Itagüí",
  "Envigado",
  "Rionegro",
  "Palmira",
  "Buenaventura",
  "Tuluá",
  "Cartago",
  "Buga",
  "Dosquebradas",
  "Floridablanca",
  "Girón",
  "Piedecuesta",
  "Barrancabermeja",
  "Chía",
  "Zipaquirá",
  "Facatativá",
  "Mosquera",
  "Madrid",
  "Funza",
  "Cajicá",
  "Fusagasugá",
  "Girardot",
  "Villeta",
  "Tocancipá",
  "Sopó",
  "Sogamoso",
  "Duitama",
  "Chiquinquirá",
  "Florencia",
  "Yopal",
  "Arauca",
  "Mocoa",
  "Ocaña",
  "Pamplona",
  "Aguachica",
  "Maicao",
  "Apartadó",
  "Turbo",
  "Tumaco",
  "Ipiales",
  "Garzón",
  "Pitalito",
  "Espinal",
  "Honda",
  "La Dorada",
  "Chinchiná",
  "Calarcá",
  "Quimbaya",
  "Sahagún",
  "Lorica",
  "Corozal",
  "Magangué",
  "Santander de Quilichao",
  "Puerto Asís",
  "San José del Guaviare",
  "Remoto",
];
