// Ciudades colombianas relevantes para filtrar busquedas.
// Bogotá primero por ser la de mayor volumen de ofertas.
export const COLOMBIAN_CITIES: string[] = [
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Bucaramanga",
  "Pereira",
  "Manizales",
  "Armenia",
  "Santa Marta",
  "Cúcuta",
  "Ibagué",
  "Neiva",
  "Villavicencio",
  "Pasto",
  "Montería",
  "Valledupar",
  "Tunja",
  "Popayán",
  "Sincelejo",
  "Riohacha",
  "Quibdó",
  "Leticia",
  "San Andrés",
  "Remoto",
];
