// Habilidades y tecnologías para autocompletado (filtros y keywords).
// Respaldo local si el backend no responde; coincide con las señales
// que usa el motor de matching (backend/app/analysis/signals.py).
export const SKILLS: string[] = [
  "Python",
  "SQL",
  "DAX",
  "Power BI",
  "Excel",
  "Power Query",
  "Power Automate",
  "Tableau",
  "Qlik",
  "Looker",
  "Looker Studio",
  "Google Sheets",
  "ETL",
  "Airflow",
  "PySpark",
  "Spark",
  "Pandas",
  "NumPy",
  "R",
  "Java",
  "JavaScript",
  "TypeScript",
  "React",
  "Angular",
  "Vue",
  "Node.js",
  "Django",
  "Flask",
  "FastAPI",
  ".NET",
  "C#",
  "Spring",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Git",
  "Linux",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Oracle",
  "SQL Server",
  "Snowflake",
  "BigQuery",
  "Redshift",
  "Databricks",
  "Hadoop",
  "Kafka",
  "Redis",
  "Machine Learning",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "NLP",
  "A/B Testing",
  "Scrum",
  "Jira",
  "Figma",
  "SAP",
  "Salesforce",
  "GraphQL",
  "REST",
  "CI/CD",
  "Jenkins",
  "Azure DevOps",
  "Data Modeling",
  "Data Warehouse",
  "VBA",
  "Access",
];
