// Habilidades y tecnologías para autocompletado (filtros, keywords,
// perfil simple y estructurado).
// Vocabulario de lo que piden las ofertas en Colombia y LATAM:
// datos/BI, ofimatica y Microsoft 365, lenguajes, frameworks,
// bases de datos, nube, IA, ERP/CRM, contabilidad, diseno,
// gestion y oficios transversales. Respaldo local si el backend no
// responde; coincide con las señales del motor de matching
// (backend/app/analysis/signals.py) mas el uso real en vacantes.
// Los inputs permiten texto libre: lo que no este aqui se puede
// agregar igual con Enter o el boton +.
export const SKILLS: string[] = [
  // --- Datos, BI y analitica ---
  "Power BI",
  "DAX",
  "Power Query",
  "Power Pivot",
  "Excel avanzado",
  "Tablas dinámicas",
  "Tableau",
  "Qlik",
  "QlikView",
  "Looker",
  "Looker Studio",
  "Google Sheets",
  "Análisis de datos",
  "EDA",
  "Limpieza de datos",
  "Transformación de datos",
  "Modelado de datos",
  "Data Warehouse",
  "Data Modeling",
  "KPIs",
  "Indicadores",
  "Dashboards",
  "Reportes",
  "Visualización de datos",
  "Análisis estadístico",
  "Estadística",
  "A/B Testing",
  "Forecasting",
  "Minería de datos",

  // --- Microsoft 365 y ofimatica ---
  "Office 365",
  "Microsoft 365",
  "Word",
  "Excel",
  "PowerPoint",
  "Outlook",
  "Teams",
  "SharePoint",
  "OneDrive",
  "OneNote",
  "Access",
  "VBA",
  "Macros",
  "Power Automate",
  "Power Apps",
  "Power Platform",
  "Power Virtual Agents",
  "Dynamics 365",
  "Ofimática",
  "Mecanografía",
  "Google Workspace",
  "Google Docs",
  "Presentaciones",
  "Redacción",

  // --- Lenguajes de programacion ---
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "C#",
  "C++",
  "C",
  "PHP",
  "Ruby",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "Dart",
  "R",
  "Scala",
  "MATLAB",
  "SQL",
  "HTML",
  "CSS",
  "SASS",
  "Bash",
  "PowerShell",
  "COBOL",
  "Visual Basic",
  // --- Desarrollo web frontend ---
  "React",
  "Angular",
  "Vue",
  "Next.js",
  "Svelte",
  "jQuery",
  "Bootstrap",
  "Tailwind",
  "Material UI",
  "Redux",
  "Responsive Design",

  // --- Backend, frameworks y librerias ---
  "Node.js",
  "Express",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  ".NET",
  "Spring",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "OpenCV",
  "YOLO",
  "NLP",
  "APIs REST",
  "REST",
  "GraphQL",
  "Microservicios",
  "WebSockets",
  "JUnit",
  "Selenium",
  "Testing",
  "QA",
  "Automatización de pruebas",

  // --- Apps moviles ---
  "Flutter",
  "React Native",
  "Android",
  "iOS",
  "Ionic",

  // --- Bases de datos ---
  "SQL Server",
  "MySQL",
  "PostgreSQL",
  "Oracle",
  "MongoDB",
  "SQLite",
  "MariaDB",
  "Snowflake",
  "BigQuery",
  "Redshift",
  "Databricks",
  "Redis",
  "Elasticsearch",
  "Firebase",
  "Supabase",
  "Administración de bases de datos",
  "SSIS",
  "SSRS",
  "SSAS",

  // --- Big Data, ETL e integracion ---
  "ETL",
  "Airflow",
  "Spark",
  "PySpark",
  "Hadoop",
  "Kafka",
  "dbt",
  "Talend",
  "Informatica",
  "Alteryx",
  "KNIME",
  "Stata",
  "SPSS",

  // --- Nube, DevOps e infraestructura ---
  "AWS",
  "Azure",
  "GCP",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "CI/CD",
  "Git",
  "GitHub",
  "GitLab",
  "Azure DevOps",
  "Linux",
  "Windows Server",
  "Redes",
  "Soporte técnico",
  "Mesa de ayuda",
  "Mantenimiento de equipos",

  // --- IA, machine learning y datos avanzados ---
  "Machine Learning",
  "Deep Learning",
  "Computer Vision",
  "Procesamiento de lenguaje natural",
  "IA generativa",
  "ChatGPT",
  "Prompt Engineering",
  "MLOps",

  // --- ERP, CRM y software empresarial ---
  "SAP",
  "SAP MM",
  "SAP FI",
  "Oracle ERP",
  "Salesforce",
  "HubSpot",
  "Zoho CRM",
  "Odoo",
  "Siigo",
  "Alegra",
  "Helisa",
  "World Office",
  "SAP Business One",

  // --- Contabilidad, finanzas y administracion ---
  "Contabilidad",
  "NIIF",
  "Facturación electrónica",
  "Nómina",
  "Seguridad social",
  "Conciliaciones bancarias",
  "Cuentas por cobrar",
  "Cuentas por pagar",
  "Presupuestos",
  "Flujo de caja",
  "Análisis financiero",
  "Excel financiero",
  "Auditoría",
  "Impuestos",
  "Retenciones",

  // --- Talento humano ---
  "Selección de personal",
  "Reclutamiento",
  "Entrevistas",
  "Contratación",
  "Bienestar laboral",
  "Capacitación",
  "Evaluación de desempeño",

  // --- Comercial, ventas y servicio ---
  "Ventas",
  "Atención al cliente",
  "Telemercadeo",
  "Call Center",
  "Servicio al cliente",
  "CRM",
  "Prospección",
  "Cierre de ventas",
  "Negociación",
  "E-commerce",
  "Mercado Libre",
  "Amazon",
  "Marketing digital",
  "SEO",
  "SEM",
  "Google Ads",
  "Meta Ads",
  "Email marketing",
  "Redes sociales",
  "Community management",
  "Copywriting",

  // --- Diseno y multimedia ---
  "Figma",
  "Photoshop",
  "Illustrator",
  "Canva",
  "Premiere",
  "After Effects",
  "Diseño gráfico",
  "Diseño UX/UI",
  "Edición de video",
  "Fotografía",

  // --- Gestion, proyectos y metodologias ---
  "Scrum",
  "Kanban",
  "Metodologías ágiles",
  "Jira",
  "Trello",
  "Notion",
  "Monday",
  "MS Project",
  "Gestión de proyectos",
  "PMP",
  "Productividad",
  "Automatización de procesos",
  "Mejora continua",
  "Lean",
  "Six Sigma",

  // --- Logistica y operaciones ---
  "Logística",
  "Inventarios",
  "Almacén",
  "Cadena de suministro",
  "Compras",
  "Importaciones",
  "Exportaciones",
  "Distribución",
  "Transporte",

  // --- Salud y oficios regulados ---
  "Seguridad y salud en el trabajo",
  "Primeros auxilios",
  "Manipulación de alimentos",
  "Bioseguridad",

  // --- Idiomas tecnicos transversales ---
  "Inglés técnico",
  "Redacción de informes",
  "Presentaciones ejecutivas",
];
